title: Bruno Dias
description:
  en: My Personal Blog
  pt: Meu Blog
author: Bruno Dias
logo: https://s.gravatar.com/avatar/e93480bce84892a336f371360e14a31d?s=80
about:
  en: Project Manager & Assistant Professor
  pt: Gerente de Projetos & Professor Assistente
index:
  en: index_en.html
  pt:
baseurl: ""
url: "https://brunojdo.github.io"

disqus_shortname: diasbruno
google_analytics:
share:
  twitter_username: Bruno_Dias_
  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
