title: Bruno Dias
description: My Personal Blog
author: Bruno Dias
logo: https://s.gravatar.com/avatar/e93480bce84892a336f371360e14a31d?s=80
about: Teacher & Project Manager

baseurl: ""
url: "https://brunojdo.github.io"

disqus_shortname: diasbruno
google_analytics:
share:
  twitter_username: Bruno_Dias_
  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
